// https://discord.com/developers/docs/resources/guild#guild-object-default-message-notification-level

export type GuildFeature =
  'ANIMATED_BANNER' |
  'ANIMATED_ICON' |
  'APPLICATION_COMMAND_PERMISSIONS_V2' |
  'AUTO_MODERATION' |
  'BANNER' |
  'COMMUNITY' |
  'CREATOR_MONETIZABLE_PROVISIONAL' |
  'CREATOR_STORE_PAGE' |
  'DEVELOPER_SUPPORT_SERVER' |
  'DISCOVERABLE' |
  'FEATURABLE' |
  'INVITES_DISABLED' |
  'INVITE_SPLASH' |
  'MEMBER_VERIFICATION_GATE_ENABLED' |
  'MORE_STICKERS' |
  'NEWS' |
  'PARTNERED' |
  'PREVIEW_ENABLED' |
  'RAID_DISABLED' |
  'ROLE_ICONS' |
  'ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE' |
  'ROLE_SUBSCRIPTIONS_ENABLED' |
  'TICKETED_EVENTS_ENABLED' |
  'VANITY_URL' |
  'VERIFIED' |
  'VIP_REGIONS' |
  'WELCOME_SCREEN_ENABLED';